image: Visual Studio 2017
skip_branch_with_pr: true
init:
# Set "build version number" to "short-commit-hash" or when tagged to "tag name"
- ps: >-
    $githash = $($env:APPVEYOR_REPO_COMMIT.Substring(0, 7))

    if ($env:APPVEYOR_REPO_TAG -eq "true") {
      Update-AppveyorBuild -Version "$($env:APPVEYOR_REPO_TAG_NAME)-$($githash)"
    } else {
      Update-AppveyorBuild -Version "build$($env:APPVEYOR_BUILD_NUMBER)-$($githash)"
    }
configuration:
- Debug
- Release
- Installer
platform: x86
environment:
  INNODIR: C:\Program Files (x86)\Inno Setup 5
install:
- cmd: >-
    git submodule update --init --recursive

    set PATH=%INNODIR%;%PATH%
build:
  project: src\rssavers.sln
  verbosity: minimal
artifacts:
- path: installer/output/*.exe
  name: installer